config/routes.rb
Spree::Core::Engine.routes.append do

  namespace :admin do
    resources :option_values do
      member do
        get :detach_image
      end
    end
  end

end

app/models/spree/app_configuration/variant_configuration.rb
module SpreeVariantOptions
  class VariantConfiguration < Spree::Preferences::Configuration
    preference :allow_select_outofstock, :boolean, :default => false
    preference :default_instock, :boolean, :default => false
    preference :main_option_type_id, :integer, :default => 1
    preference :main_option_type_label, :string, :default => 'color'
    preference :option_value_url, :string, :default => '/spree/option_values/:id/:style/:basename.:extension'
    preference :option_value_path, :string, :default => ':rails_root/public/spree/option_values/:id/:style/:basename.:extension'
    preference :option_value_styles, :string, default: "{\"small\":\"40x30#\",\"large\":\"140x110#\"}"
    preference :option_value_default_style, :string, default: 'small'
  end
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do

  has_attached_file :image,
    :styles        => { mini: '32x32>', normal: '128x128>' },
    :default_style => SpreeVariantOptions::VariantConfig[:option_value_default_style],
    :url           => SpreeVariantOptions::VariantConfig[:option_value_url],
    :path          => SpreeVariantOptions::VariantConfig[:option_value_path]

  def has_image?
    image_file_name && !image_file_name.empty?
  end

  default_scope { order("#{quoted_table_name}.position") }
  scope :for_product, lambda { |product| select("DISTINCT #{table_name}.*").where("spree_option_values_variants.variant_id IN (?)", product.variant_ids).joins(:variants) }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  def option_values
    @_option_values ||= Spree::OptionValue.for_product(self)
  end

  def grouped_option_values
    @_grouped_option_values ||= option_values.group_by(&:option_type)
    @_grouped_option_values.sort_by { |option_type, option_values| option_type.position }.reverse 
  end

  def variants_for_option_value(value)
    @_variant_option_values ||= variants.includes(:option_values)
    @_variant_option_values.select { |i| i.option_value_ids.include?(value.id) }
  end

  def variant_options_hash(currency)
    return @_variant_options_hash if @_variant_options_hash
    hash = {}
    variants.includes(:option_values).each do |variant|
      variant.option_values.each do |ov|
        otid = ov.option_type_id.to_s
        ovid = ov.id.to_s
        hash[otid] ||= {}
        hash[otid][ovid] ||= {}
        hash[otid][ovid][variant.id.to_s] = variant.to_hash(currency)
      end
    end
    @_variant_options_hash = hash
  end

end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  include ActionView::Helpers::NumberHelper

  def to_hash(currency)
    actual_price  = self.price_in(currency).money
    #actual_price += Calculator::Vat.calculate_tax_on(self) if Spree::Config[:show_price_inc_vat]
    {
      :id    => self.id,
      :in_stock => self.in_stock?,
      :price => actual_price
    }
  end

end

app/controllers/concerns/product_extensions.rb
module ProductExtensions
  extend ActiveSupport::Concern

  included do
    singleton_class.prepend ClassMethods
    prepend InstanceMethods
  end

  module ClassMethods

  end

  module InstanceMethods
    def show
      super
      @main_option_value = params[SpreeVariantOptions::VariantConfig.main_option_type_label]
    end
  end

end

app/controllers/spree/admin/images_controller_decorator.rb
Spree::Admin::ImagesController.class_eval do
  alias_method :super_load_index_data, :load_index_data

  # Called in a before_filter
  def load_index_data
    super_load_index_data

    @grouped_option_values ||= @product.option_values.group_by(&:option_type)
    @grouped_option_values.sort_by { |option_type, option_values| option_type.position }
  end

  # Called in a create.before
  def set_viewable
    viewable_id = params[:image][:viewable_id]

    if viewable_id.is_a?(Hash)
      @product.errors.add(:attachment, 'Erro')
      option_values_array = viewable_id.map {|option_type, option_values| option_values.map(&:to_i) }
      option_values_combinations = option_values_array.shift
      option_values_array.each do |option_value|
        option_values_combinations = option_values_combinations.product(option_value)
      end
      option_values_combinations = option_values_combinations.map(&:flatten) if option_values_combinations.count > 1

      @product.variants.each do |variant|
        option_values_combinations.each do |ov_combination|
          variant_option_ids = variant.option_values.pluck(:id)

          if ([ov_combination].flatten - variant_option_ids).empty?
            create_image(variant, permitted_resource_params)
          end
        end
      end
    else
      viewable_id = params[:master_option] if params[:master_option]
      @image.viewable_type = 'Spree::Variant'
      @image.viewable_id = viewable_id
    end
  end

  private

  def create_image(variant, image_attributes)
    image = Spree::Image.new(permitted_resource_params)
    image.viewable_type = 'Spree::Variant'
    image.viewable_id = variant.id
    variant.images << image
    variant.save
  end
end

app/controllers/spree/admin/option_values_controller_decorator.rb
Spree::Admin::OptionValuesController.class_eval do
  def detach_image
    @option_value = Spree::OptionValue.find(params[:id])
    @option_value.image = nil
    @option_value.save
    redirect_to edit_admin_option_type_url(@option_value.option_type)
  end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.include ProductExtensions

app/views/spree/admin/images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label Spree.t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>

    <%= content_tag :div, '', id: 'error-message' , data: { one_option_error: Spree.t(:one_option_per_type_must_be_selected) } %>
    <% if @grouped_option_values.empty? %>
      <div data-hook="variant" class="field">
        <%= f.label Spree::Variant.model_name.human %><br>
        <%= f.select :viewable_id, @variants, {}, {:class => 'select2 fullwidth'} %>
      </div>
    <% else %>
      <div data-hook="variant" class="field">
        <%= f.label I18n.t(:other, scope: 'activerecord.models.spree/variant') %><br>

        <%# Master variant associates an image for all option_values and option_types combinations  %>
        <%= check_box_tag "master_option", @product.master.id, false, :id => "master_option" %>
        <%= label_tag "master_option", Spree.t(:all) %>
        <ul></ul>

        <% @grouped_option_values.each do |option_type, option_values| %>
          <div class="option-type-field">
            <%= check_box_tag "option_types[]", option_type.id, (params[:option_types] || []).include?(option_type.id.to_s), :id => "option_type_#{option_type.id}", :class => "option-type" %>
            <%= label_tag "option_type_#{option_type.id}", option_type.presentation %>

            <ul class="option-type-values">
              <%  puts "option_values: #{option_values}"
              option_values.each_with_index do |option_value, index| %>
                <li>
                  <%= check_box_tag "image[viewable_id][#{option_type.id}][]", option_value.id, false, class: 'option-value', id: "#{option_value.id}_#{index}" %>
                  <%= label_tag "image[viewable_id][#{option_type.id}][#{option_type.id}]", option_value.presentation, for: "#{option_value.id}_#{index}" %>
                </li>
              <% end %>
            </ul>
          </div>
          <br>
        <% end %>
      </div>
    <% end %>

  </div>


  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, :rows => 4, :class => 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>








<script type="text/javascript">
//<![CDATA[
  (function($){

    $("input.option-type").change(function() {
      $(this).parents(".option-type-field").find("input.option-value").attr("checked", this.checked);
    });

    $("input.option-value").change(function() {
      var any_checked = false;
      $(this).parents(".option-type-values").find("input.option-value").each(function(i, el) {
        any_checked = any_checked || el.checked;
      });
      $(this).parents(".option-type-field").find("input.option-type").attr("checked", any_checked);
    });

  })(jQuery);
  //]]>
  </script>

app/views/spree/admin/option_types/_option_value_fields.html.erb
<tr class="option_value fields" id="spree_<%= dom_id(f.object) %>"  data-hook="option_value" class="<%= cycle('odd', 'even')%>">
	<td class="no-border">
		<span class="handle"></span>
		<%= f.hidden_field :id %>
	</td>
	<td class="name"><%= f.text_field :name %></td>
	<td class="presentation"><%= f.text_field :presentation %></td>
	<td align="center">
    <% if f.object.has_image? %>
      <%= image_tag f.object.image.url(:small) %>
      <%= link_to_with_icon 'icon-remove', '', detach_image_admin_option_value_path(f.object), title: Spree.t(:detach_image) %>
    <% end %>
  </td>
	<td><%= f.file_field :image %></td>
	<td class="actions actions-1 text-center"><%= link_to_icon_remove_fields f %></td>
</tr>

app/views/spree/admin/option_values/_table_header.html.erb
<tr>
  <th colspan="2"><%= Spree.t(:name) %></th>
  <th><%= Spree.t(:display) %></th>
  <th><%= Spree.t(:preview) %></th>
  <th><%= Spree.t(:attach) %></th>
</tr>

app/views/spree/products/_variant_options.html.erb
<% if @product.has_variants? and !display_price(@product).nil? %>
  <div id="product-variants">
    <% index = 0 %>
    <% @product.grouped_option_values.each do |type, values| %>
      <div id="<%= dom_id(type) %>" class="variant-options index-<%= index %>">
        <h6 class="variant-option-type">
          <%= label_tag 'option-value-name', Spree.t(:select_a, :index => index + 1, :name => type.presentation) %>&nbsp;
          <strong class='selection'></strong>
          <%= link_to "", "#clear", :class => "icon-remove clear-button clear-index-#{index}" %>
        </h6>

        <ul class="variant-option-values" class='inline'>
        <% values.sort_by(&:position).each do |value| %>
          <% classes = ["option-value"] %>
          <% unless (variants = @product.variants_for_option_value(value)).empty? %>
            <% classes << ( variants.any? { |v| v.in_stock? } ? "in-stock" : "out-of-stock" ) if index == 0 %>
            <% classes << 'with-image' if value.has_image? %>
            <li><%= link_to value.has_image? ? image_tag(value.image.url, :alt => value.presentation) : content_tag(:span, value.presentation), "#", :title => value.presentation, :class => classes.join(" "), :rel => "#{type.id}-#{value.id}" %></li>
          <% end %>
        <% end %>
          <li class="clear"></li>
        </ul>
      </div>
      <% index += 1 %>
    <% end %>

    <%= hidden_field_tag "products[#{@product.id}]", "", :id => "variant_id", :class => "hidden" %>
    <%= hidden_field_tag :variant_id, "", :class => "hidden" %>
    
    <script type="text/javascript">
    //<![CDATA[
      var variant_options = new VariantOptions({
        options: <%== @product.variant_options_hash(current_currency).to_json -%>,
        track_inventory_levels: <%==  !!Spree::Config[:track_inventory_levels] -%>,
        allow_select_outofstock: <%== !!SpreeVariantOptions::VariantConfig[:allow_select_outofstock] -%>,
        default_instock: <%== !!SpreeVariantOptions::VariantConfig[:default_instock] -%>,
        i18n: <%== {:out_of_stock => Spree.t(:out_of_stock), :variant_options_select => Spree.t(:variant_options_select) }.to_json -%>
      });
      $(function() {
        url = $.urlParam('<%=SpreeVariantOptions::VariantConfig.main_option_type_label%>')
        $("[title="+ url +"]").click();
      });
    //]]>
    </script>
  </div>
<% end%>